/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mcdeamon4j;

import org.junit.jupiter.api.Test;

import iafenvoy.MCDeamon4J.Main;

class AppTest {
    @Test void appHasAGreeting() {
        Main.main(null);
    }
}
